name: Ověření HACS

# on:
#   push:
#   pull_request:
#   schedule:
#     - cron: "0 0 * * *"
  # Workflow se spouští pouze ručně z karty Actions na GitHubu.
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    name: Validace HACS
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@main
        with:
          category: plugin
          comment: false
